// Package keymanager implements AeroLLM virtual keys: gateway API keys that are
// generated by an administrator (or a team admin), carry per-key limits
// (allowed models, budget, rate limits, expiry) and are validated by the
// gateway on every request.
//
// Security model:
//   - Keys are 256-bit values from crypto/rand, rendered as
//     VirtualKeyPrefix + base64url (e.g. "sk-aero-3J7...").
//   - Only the SHA-256 hash of a key is ever stored. The plaintext is returned
//     exactly once, from Generate/Regenerate, and is never logged or persisted.
//   - Lookups are by hash; the stored hash is additionally compared with
//     crypto/subtle so no secret-dependent comparison leaks timing.
package keymanager

import (
	"context"
	"crypto/rand"
	"crypto/sha256"
	"crypto/subtle"
	"encoding/base64"
	"encoding/hex"
	"errors"
	"fmt"
	"maps"
	"math"
	"slices"
	"strconv"
	"strings"
	"sync"
	"time"
	"unicode"
)

// VirtualKeyPrefix is the distinctive prefix of every key generated by
// Manager. It deliberately differs from the generic "sk-" prefix so that
// static gateway keys such as the default admin key "sk-demo" are never
// mistaken for virtual keys (see IsVirtualKey).
const VirtualKeyPrefix = "sk-aero-"

// keyEntropyBytes is the number of random bytes in a generated key (256 bits).
const keyEntropyBytes = 32

// prefixHintLen is the number of characters of the key kept as a non-secret
// display hint (the fixed prefix plus 6 random characters = 36 bits).
const prefixHintLen = len(VirtualKeyPrefix) + 6

// Metadata keys read by the rate-limit header middleware. Manager always
// mirrors VirtualKey.RateLimitRPS (float64) and RateLimitTPM (int) into
// Metadata under these keys so existing middleware keeps working.
const (
	MetadataRateLimitRPS = "rate_limit_rps"
	MetadataRateLimitTPM = "rate_limit_tpm"
)

// Validation limits.
const (
	maxModels        = 256
	maxModelLen      = 256
	maxAliases       = 64
	maxIDLen         = 128
	maxMetadataKeys  = 64
	maxBudgetUSD     = 1e12
	maxRateLimitRPS  = 1e6
	maxRateLimitTPM  = 1 << 40
	maxKeyLifetime   = 100 * 365 * 24 * time.Hour
	hashHexLen       = sha256.Size * 2
	defaultBodyLimit = 64 << 10
)

// KeyStatus represents the lifecycle state of a virtual key.
type KeyStatus string

const (
	StatusActive  KeyStatus = "active"
	StatusDeleted KeyStatus = "deleted"
	StatusExpired KeyStatus = "expired"
)

// KeyRole is the management role of a virtual key.
type KeyRole string

const (
	// RoleMember keys can only use the gateway and inspect/revoke themselves
	// (and view keys of their own team).
	RoleMember KeyRole = ""
	// RoleTeamAdmin keys can additionally generate, update, block and revoke
	// member keys of their own team. They can never act outside their team,
	// mint other team admins, or change team budgets.
	RoleTeamAdmin KeyRole = "team_admin"
)

// Errors returned by Manager. Callers should use errors.Is.
var (
	ErrEmptyKey       = errors.New("keymanager: empty key")
	ErrKeyRevoked     = errors.New("keymanager: key revoked")
	ErrKeyBlocked     = errors.New("keymanager: key blocked")
	ErrKeyExpired     = errors.New("keymanager: key expired")
	ErrBudgetExceeded = errors.New("keymanager: key budget exceeded")
	ErrInvalidAmount  = errors.New("keymanager: spend amount must be a finite, non-negative number")
)

// ValidationError reports an invalid request field. Its message is safe to
// return to clients.
type ValidationError struct {
	Field  string
	Reason string
}

func (e *ValidationError) Error() string {
	return fmt.Sprintf("invalid %s: %s", e.Field, e.Reason)
}

func invalid(field, reason string) error { return &ValidationError{Field: field, Reason: reason} }

// VirtualKey is the stored representation of a virtual key. It never
// contains the plaintext key.
type VirtualKey struct {
	KeyHash   string                 `json:"key_hash"`
	HashedKey string                 `json:"-"`
	Prefix    string                 `json:"prefix"`
	Models    []string               `json:"models"`
	MaxBudget float64                `json:"max_budget"`
	Aliases   []string               `json:"aliases"`
	Metadata  map[string]interface{} `json:"metadata"`
	UserID    string                 `json:"user_id"`
	TeamID    string                 `json:"team_id"`
	TenantID  string                 `json:"tenant_id"`
	CreatedAt time.Time              `json:"created_at"`
	ExpiresAt time.Time              `json:"expires_at"`
	Status    KeyStatus              `json:"status"`
	// CreatedAtMs is CreatedAt in Unix milliseconds.
	CreatedAtMs int64 `json:"created_at_ms"`

	// Spend is the accumulated spend in USD in the current budget period.
	Spend float64 `json:"spend"`
	// BudgetDuration, if set (e.g. "30d", "24h"), resets Spend periodically.
	BudgetDuration string `json:"budget_duration,omitempty"`
	// BudgetResetAt is when Spend is next reset (zero if no BudgetDuration).
	BudgetResetAt time.Time `json:"budget_reset_at,omitempty"`
	// Blocked keys are rejected by Validate but can be unblocked.
	Blocked bool `json:"blocked"`
	// Role is the management role of the key.
	Role KeyRole `json:"role,omitempty"`
	// RateLimitRPS / RateLimitTPM are per-key rate limits (0 = gateway default).
	RateLimitRPS float64 `json:"rate_limit_rps,omitempty"`
	RateLimitTPM int     `json:"rate_limit_tpm,omitempty"`
	// UpdatedAt is the time of the last management change.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
}

// Clone returns a deep-enough copy of the key: slices and the top-level
// metadata map are copied so the clone can be mutated independently.
func (vk *VirtualKey) Clone() *VirtualKey {
	if vk == nil {
		return nil
	}
	out := *vk
	if vk.Models != nil {
		out.Models = append([]string(nil), vk.Models...)
	}
	if vk.Aliases != nil {
		out.Aliases = append([]string(nil), vk.Aliases...)
	}
	if vk.Metadata != nil {
		out.Metadata = maps.Clone(vk.Metadata)
	}
	return &out
}

// AllowsModel reports whether the key may be used with model. A key with no
// model restrictions allows every model. Entries match case-insensitively;
// "*" allows everything and a trailing "*" is a prefix wildcard
// (e.g. "gpt-4*" allows "gpt-4o").
func (vk *VirtualKey) AllowsModel(model string) bool {
	if vk == nil {
		return false
	}
	if len(vk.Models) == 0 {
		return true
	}
	model = strings.ToLower(strings.TrimSpace(model))
	if model == "" {
		return false
	}
	for _, m := range vk.Models {
		m = strings.ToLower(strings.TrimSpace(m))
		switch {
		case m == "*":
			return true
		case strings.HasSuffix(m, "*"):
			if strings.HasPrefix(model, strings.TrimSuffix(m, "*")) {
				return true
			}
		case m == model:
			return true
		}
	}
	return false
}

// EffectiveSpend returns the spend that counts against the budget at time
// now, taking a pending budget-period reset into account.
func (vk *VirtualKey) EffectiveSpend(now time.Time) float64 {
	if vk == nil {
		return 0
	}
	if vk.BudgetDuration != "" && !vk.BudgetResetAt.IsZero() && !now.Before(vk.BudgetResetAt) {
		return 0
	}
	return vk.Spend
}

// BudgetExceeded reports whether the key has a budget and has spent all of it.
func (vk *VirtualKey) BudgetExceeded() bool {
	if vk == nil || vk.MaxBudget <= 0 {
		return false
	}
	return vk.EffectiveSpend(time.Now()) >= vk.MaxBudget
}

// RemainingBudget returns the remaining budget in USD. ok is false when the
// key has no budget limit.
func (vk *VirtualKey) RemainingBudget() (remaining float64, ok bool) {
	if vk == nil || vk.MaxBudget <= 0 {
		return 0, false
	}
	r := vk.MaxBudget - vk.EffectiveSpend(time.Now())
	if r < 0 {
		r = 0
	}
	return r, true
}

// IsExpired reports whether the key has an expiry that has passed.
func (vk *VirtualKey) IsExpired(now time.Time) bool {
	return vk != nil && !vk.ExpiresAt.IsZero() && !now.Before(vk.ExpiresAt)
}

// usable returns nil if the key may authenticate at time now. Budget is not
// checked here.
func (vk *VirtualKey) usable(now time.Time) error {
	switch {
	case vk.Status == StatusDeleted:
		return ErrKeyRevoked
	case vk.Status == StatusExpired || vk.IsExpired(now):
		return ErrKeyExpired
	case vk.Status != StatusActive:
		return fmt.Errorf("keymanager: key status %q", vk.Status)
	case vk.Blocked:
		return ErrKeyBlocked
	}
	return nil
}

// KeyStore is the interface for persisting virtual keys. Implementations must
// be safe for concurrent use. Get/List should return copies (see
// InMemoryKeyStore) so callers cannot mutate stored state.
type KeyStore interface {
	Create(ctx context.Context, key *VirtualKey) error
	Get(ctx context.Context, keyHash string) (*VirtualKey, error)
	GetByPrefix(ctx context.Context, prefix string) (*VirtualKey, error)
	Update(ctx context.Context, key *VirtualKey) error
	Delete(ctx context.Context, keyHash string) error
	List(ctx context.Context) ([]*VirtualKey, error)
}

// AtomicKeyUpdater is optionally implemented by stores that can apply a
// read-modify-write atomically. Manager uses it for spend tracking and
// management updates; for other stores Manager serializes updates itself.
type AtomicKeyUpdater interface {
	UpdateFunc(ctx context.Context, keyHash string, fn func(*VirtualKey) error) (*VirtualKey, error)
}

// GenerateRequest is the payload for POST /key/generate.
type GenerateRequest struct {
	Models    []string               `json:"models"`
	Duration  string                 `json:"duration"`
	MaxBudget float64                `json:"max_budget"`
	Aliases   []string               `json:"aliases"`
	Metadata  map[string]interface{} `json:"metadata"`
	UserID    string                 `json:"user_id"`
	TeamID    string                 `json:"team_id"`

	TenantID       string  `json:"tenant_id,omitempty"`
	BudgetDuration string  `json:"budget_duration,omitempty"`
	RateLimitRPS   float64 `json:"rate_limit_rps,omitempty"`
	RateLimitTPM   int     `json:"rate_limit_tpm,omitempty"`
	Role           KeyRole `json:"role,omitempty"`
	Blocked        bool    `json:"blocked,omitempty"`
}

// GenerateResponse is the response for POST /key/generate. It is the only
// place a plaintext key is ever returned.
type GenerateResponse struct {
	KeyHash string `json:"key_hash"`
	Key     string `json:"key"`
	// Expires is RFC 3339, or "" when the key never expires.
	Expires string `json:"expires"`
	Token   string `json:"token"`
	Prefix  string `json:"prefix,omitempty"`
}

// InfoRequest is the payload for POST /key/info.
type InfoRequest struct {
	KeyHash string `json:"key_hash"`
	Key     string `json:"key"`
	Token   string `json:"token"`
}

// DeleteRequest is the payload for POST /key/delete.
type DeleteRequest struct {
	KeyHash string `json:"key_hash"`
	Key     string `json:"key"`
	Token   string `json:"token"`
}

// UpdateRequest is the payload for POST /key/update. Nil fields are left
// unchanged.
type UpdateRequest struct {
	KeyHash string `json:"key_hash"`
	Key     string `json:"key"`
	Token   string `json:"token"`

	Models         *[]string              `json:"models,omitempty"`
	MaxBudget      *float64               `json:"max_budget,omitempty"`
	Duration       *string                `json:"duration,omitempty"`
	Aliases        *[]string              `json:"aliases,omitempty"`
	Metadata       map[string]interface{} `json:"metadata,omitempty"`
	BudgetDuration *string                `json:"budget_duration,omitempty"`
	RateLimitRPS   *float64               `json:"rate_limit_rps,omitempty"`
	RateLimitTPM   *int                   `json:"rate_limit_tpm,omitempty"`
	Blocked        *bool                  `json:"blocked,omitempty"`
	Role           *KeyRole               `json:"role,omitempty"`
	ResetSpend     bool                   `json:"reset_spend,omitempty"`
}

// InfoResponse is the response for POST /key/info. It never contains the
// plaintext key.
type InfoResponse struct {
	KeyHash   string                 `json:"key_hash"`
	Models    []string               `json:"models"`
	MaxBudget float64                `json:"max_budget"`
	Aliases   []string               `json:"aliases"`
	Metadata  map[string]interface{} `json:"metadata"`
	Status    KeyStatus              `json:"status"`
	Created   time.Time              `json:"created_at"`
	Expires   time.Time              `json:"expires_at"`

	Prefix         string     `json:"prefix"`
	Spend          float64    `json:"spend"`
	UserID         string     `json:"user_id,omitempty"`
	TeamID         string     `json:"team_id,omitempty"`
	TenantID       string     `json:"tenant_id,omitempty"`
	Role           KeyRole    `json:"role,omitempty"`
	Blocked        bool       `json:"blocked"`
	RateLimitRPS   float64    `json:"rate_limit_rps,omitempty"`
	RateLimitTPM   int        `json:"rate_limit_tpm,omitempty"`
	BudgetDuration string     `json:"budget_duration,omitempty"`
	BudgetResetAt  *time.Time `json:"budget_reset_at,omitempty"`
}

func infoFromKey(vk *VirtualKey, now time.Time) *InfoResponse {
	out := &InfoResponse{
		KeyHash:        vk.KeyHash,
		Models:         append([]string(nil), vk.Models...),
		MaxBudget:      vk.MaxBudget,
		Aliases:        append([]string(nil), vk.Aliases...),
		Metadata:       maps.Clone(vk.Metadata),
		Status:         vk.Status,
		Created:        vk.CreatedAt,
		Expires:        vk.ExpiresAt,
		Prefix:         vk.Prefix,
		Spend:          vk.EffectiveSpend(now),
		UserID:         vk.UserID,
		TeamID:         vk.TeamID,
		TenantID:       vk.TenantID,
		Role:           vk.Role,
		Blocked:        vk.Blocked,
		RateLimitRPS:   vk.RateLimitRPS,
		RateLimitTPM:   vk.RateLimitTPM,
		BudgetDuration: vk.BudgetDuration,
	}
	if vk.Status == StatusActive && vk.IsExpired(now) {
		out.Status = StatusExpired
	}
	if !vk.BudgetResetAt.IsZero() {
		t := vk.BudgetResetAt
		out.BudgetResetAt = &t
	}
	return out
}

// Manager handles virtual key lifecycle operations. It is safe for
// concurrent use.
type Manager struct {
	store KeyStore

	// masterKeyHash is SHA-256 of the configured master key; masterUsable is
	// false when the master key is empty, too short or a well-known default,
	// in which case it is never accepted as an admin credential.
	masterKeyHash [sha256.Size]byte
	masterUsable  bool

	mu  sync.Mutex // serializes read-modify-write for non-atomic stores
	now func() time.Time
}

// MinMasterKeyLength is the minimum length for the master key to be accepted
// as an admin credential by the key-management handlers.
const MinMasterKeyLength = 16

var weakMasterKeys = map[string]bool{
	"default-master-key": true,
	"changeme":           true,
	"master-key":         true,
	"sk-demo":            true,
}

// NewManager creates a new key manager. masterKey is the administrator
// credential for the key-management API; it is only honoured if it is at
// least MinMasterKeyLength characters and not a well-known default such as
// "default-master-key" (see MasterKeyUsable). It is not used to derive key
// hashes, so rotating it does not invalidate issued keys.
func NewManager(store KeyStore, masterKey string) *Manager {
	if store == nil {
		store = NewInMemoryKeyStore()
	}
	m := &Manager{store: store, now: time.Now}
	mk := strings.TrimSpace(masterKey)
	if len(mk) >= MinMasterKeyLength && !weakMasterKeys[strings.ToLower(mk)] {
		m.masterKeyHash = sha256.Sum256([]byte(mk))
		m.masterUsable = true
	}
	return m
}

// MasterKeyUsable reports whether the configured master key is strong enough
// to be accepted as an admin credential.
func (m *Manager) MasterKeyUsable() bool { return m != nil && m.masterUsable }

// IsMasterKey reports, in constant time, whether token is the master key.
// It always returns false when MasterKeyUsable is false.
func (m *Manager) IsMasterKey(token string) bool {
	if m == nil || !m.masterUsable {
		return false
	}
	h := sha256.Sum256([]byte(stripBearer(token)))
	return subtle.ConstantTimeCompare(h[:], m.masterKeyHash[:]) == 1
}

// Store returns the underlying key store.
func (m *Manager) Store() KeyStore { return m.store }

// HashKey returns the lowercase hex SHA-256 of a plaintext key; this is the
// identifier under which the key is stored (VirtualKey.KeyHash).
func HashKey(key string) string {
	sum := sha256.Sum256([]byte(key))
	return hex.EncodeToString(sum[:])
}

// newPlaintextKey returns a fresh key with 256 bits of entropy.
func newPlaintextKey() (string, error) {
	raw := make([]byte, keyEntropyBytes)
	if _, err := rand.Read(raw); err != nil {
		return "", fmt.Errorf("keymanager: generate random key: %w", err)
	}
	return VirtualKeyPrefix + base64.RawURLEncoding.EncodeToString(raw), nil
}

// ParseDuration parses a key lifetime or budget period. It accepts Go
// durations ("1h30m", "1ms") plus day and week suffixes ("30d", "2w").
// "" and "0" mean "no duration" and return 0. Negative values are rejected.
func ParseDuration(s string) (time.Duration, error) {
	s = strings.TrimSpace(s)
	if s == "" || s == "0" {
		return 0, nil
	}
	var d time.Duration
	if n := len(s); n > 1 && (s[n-1] == 'd' || s[n-1] == 'w') {
		f, err := strconv.ParseFloat(s[:n-1], 64)
		if err != nil || math.IsNaN(f) || math.IsInf(f, 0) {
			return 0, fmt.Errorf("invalid duration %q", s)
		}
		unit := 24 * time.Hour
		if s[n-1] == 'w' {
			unit *= 7
		}
		if f < 0 || f*float64(unit) > float64(maxKeyLifetime) {
			return 0, fmt.Errorf("duration %q out of range", s)
		}
		d = time.Duration(f * float64(unit))
	} else {
		var err error
		d, err = time.ParseDuration(s)
		if err != nil {
			return 0, fmt.Errorf("invalid duration %q", s)
		}
	}
	if d < 0 {
		return 0, fmt.Errorf("duration %q must not be negative", s)
	}
	if d > maxKeyLifetime {
		return 0, fmt.Errorf("duration %q out of range", s)
	}
	return d, nil
}

func validText(field, v string, maxLen int) error {
	if len(v) > maxLen {
		return invalid(field, fmt.Sprintf("longer than %d characters", maxLen))
	}
	for _, r := range v {
		if unicode.IsControl(r) {
			return invalid(field, "contains control characters")
		}
	}
	return nil
}

func validList(field string, vals []string, maxItems, maxLen int) error {
	if len(vals) > maxItems {
		return invalid(field, fmt.Sprintf("more than %d entries", maxItems))
	}
	for _, v := range vals {
		if strings.TrimSpace(v) == "" {
			return invalid(field, "contains an empty entry")
		}
		if err := validText(field, v, maxLen); err != nil {
			return err
		}
	}
	return nil
}

func validBudget(field string, v float64) error {
	if math.IsNaN(v) || math.IsInf(v, 0) || v < 0 || v > maxBudgetUSD {
		return invalid(field, "must be a finite number between 0 and 1e12")
	}
	return nil
}

func validRPS(v float64) error {
	if math.IsNaN(v) || math.IsInf(v, 0) || v < 0 || v > maxRateLimitRPS {
		return invalid("rate_limit_rps", "must be a finite number between 0 and 1e6")
	}
	return nil
}

func validTPM(v int) error {
	if v < 0 || v > maxRateLimitTPM {
		return invalid("rate_limit_tpm", "out of range")
	}
	return nil
}

func validRole(r KeyRole) error {
	if r != RoleMember && r != RoleTeamAdmin {
		return invalid("role", `must be "" or "team_admin"`)
	}
	return nil
}

// numberFromMetadata extracts a finite number from a metadata value.
func numberFromMetadata(v interface{}) (float64, bool) {
	var f float64
	switch t := v.(type) {
	case float64:
		f = t
	case float32:
		f = float64(t)
	case int:
		f = float64(t)
	case int64:
		f = float64(t)
	case string:
		p, err := strconv.ParseFloat(strings.TrimSpace(t), 64)
		if err != nil {
			return 0, false
		}
		f = p
	default:
		return 0, false
	}
	if math.IsNaN(f) || math.IsInf(f, 0) {
		return 0, false
	}
	return f, true
}

// applyRateLimitMetadata normalises rate limits between the typed fields and
// the metadata map read by the rate-limit middleware.
func applyRateLimitMetadata(vk *VirtualKey) error {
	if vk.Metadata == nil {
		vk.Metadata = map[string]interface{}{}
	}
	if vk.RateLimitRPS == 0 {
		if v, ok := vk.Metadata[MetadataRateLimitRPS]; ok {
			f, ok := numberFromMetadata(v)
			if !ok {
				return invalid("metadata.rate_limit_rps", "must be a number")
			}
			vk.RateLimitRPS = f
		}
	}
	if vk.RateLimitTPM == 0 {
		if v, ok := vk.Metadata[MetadataRateLimitTPM]; ok {
			f, ok := numberFromMetadata(v)
			if !ok || f < 0 || f > maxRateLimitTPM {
				return invalid("metadata.rate_limit_tpm", "must be a non-negative number")
			}
			vk.RateLimitTPM = int(f)
		}
	}
	if err := validRPS(vk.RateLimitRPS); err != nil {
		return err
	}
	if err := validTPM(vk.RateLimitTPM); err != nil {
		return err
	}
	delete(vk.Metadata, MetadataRateLimitRPS)
	delete(vk.Metadata, MetadataRateLimitTPM)
	if vk.RateLimitRPS > 0 {
		vk.Metadata[MetadataRateLimitRPS] = vk.RateLimitRPS
	}
	if vk.RateLimitTPM > 0 {
		vk.Metadata[MetadataRateLimitTPM] = vk.RateLimitTPM
	}
	return nil
}

func validateGenerate(req *GenerateRequest) error {
	if err := validList("models", req.Models, maxModels, maxModelLen); err != nil {
		return err
	}
	if err := validList("aliases", req.Aliases, maxAliases, maxModelLen); err != nil {
		return err
	}
	if err := validBudget("max_budget", req.MaxBudget); err != nil {
		return err
	}
	for field, v := range map[string]string{"user_id": req.UserID, "team_id": req.TeamID, "tenant_id": req.TenantID} {
		if err := validText(field, v, maxIDLen); err != nil {
			return err
		}
	}
	if len(req.Metadata) > maxMetadataKeys {
		return invalid("metadata", fmt.Sprintf("more than %d keys", maxMetadataKeys))
	}
	if err := validRole(req.Role); err != nil {
		return err
	}
	if req.Role == RoleTeamAdmin && strings.TrimSpace(req.TeamID) == "" {
		return invalid("role", "team_admin keys require a team_id")
	}
	return nil
}

// Generate creates a new virtual key, persists its hash, and returns the
// plaintext key. This is the only time the plaintext is available.
func (m *Manager) Generate(ctx context.Context, req *GenerateRequest) (*GenerateResponse, error) {
	if req == nil {
		req = &GenerateRequest{}
	}
	if err := validateGenerate(req); err != nil {
		return nil, err
	}
	lifetime, err := ParseDuration(req.Duration)
	if err != nil {
		return nil, invalid("duration", err.Error())
	}
	budgetPeriod, err := ParseDuration(req.BudgetDuration)
	if err != nil {
		return nil, invalid("budget_duration", err.Error())
	}

	now := m.now().UTC()
	vk := &VirtualKey{
		Models:       append([]string(nil), req.Models...),
		MaxBudget:    req.MaxBudget,
		Aliases:      append([]string(nil), req.Aliases...),
		Metadata:     maps.Clone(req.Metadata),
		UserID:       req.UserID,
		TeamID:       req.TeamID,
		TenantID:     req.TenantID,
		Status:       StatusActive,
		CreatedAt:    now,
		CreatedAtMs:  now.UnixMilli(),
		UpdatedAt:    now,
		Blocked:      req.Blocked,
		Role:         req.Role,
		RateLimitRPS: req.RateLimitRPS,
		RateLimitTPM: req.RateLimitTPM,
	}
	if lifetime > 0 {
		vk.ExpiresAt = now.Add(lifetime)
	}
	if budgetPeriod > 0 {
		vk.BudgetDuration = strings.TrimSpace(req.BudgetDuration)
		vk.BudgetResetAt = now.Add(budgetPeriod)
	}
	if err := applyRateLimitMetadata(vk); err != nil {
		return nil, err
	}

	var key string
	for attempt := 0; ; attempt++ {
		key, err = newPlaintextKey()
		if err != nil {
			return nil, err
		}
		vk.KeyHash = HashKey(key)
		vk.HashedKey = vk.KeyHash
		vk.Prefix = key[:prefixHintLen]
		err = m.store.Create(ctx, vk.Clone())
		if err == nil {
			break
		}
		// A collision of 256-bit random keys is practically impossible, but
		// never overwrite an existing key.
		if !errors.Is(err, ErrKeyExists) || attempt >= 2 {
			return nil, fmt.Errorf("keymanager: store key: %w", err)
		}
	}

	expires := ""
	if !vk.ExpiresAt.IsZero() {
		expires = vk.ExpiresAt.Format(time.RFC3339)
	}
	return &GenerateResponse{
		KeyHash: vk.KeyHash,
		Key:     key,
		Expires: expires,
		Token:   key,
		Prefix:  vk.Prefix,
	}, nil
}

// update applies fn to the stored key atomically.
func (m *Manager) update(ctx context.Context, keyHash string, fn func(*VirtualKey) error) (*VirtualKey, error) {
	if !isKeyHash(keyHash) {
		return nil, ErrKeyNotFound
	}
	wrapped := func(vk *VirtualKey) error {
		if err := fn(vk); err != nil {
			return err
		}
		vk.UpdatedAt = m.now().UTC()
		return nil
	}
	if au, ok := m.store.(AtomicKeyUpdater); ok {
		return au.UpdateFunc(ctx, keyHash, wrapped)
	}
	m.mu.Lock()
	defer m.mu.Unlock()
	vk, err := m.store.Get(ctx, keyHash)
	if err != nil {
		return nil, err
	}
	vk = vk.Clone()
	if err := wrapped(vk); err != nil {
		return nil, err
	}
	if err := m.store.Update(ctx, vk.Clone()); err != nil {
		return nil, err
	}
	return vk, nil
}

// get returns a private copy of a stored key.
func (m *Manager) get(ctx context.Context, keyHash string) (*VirtualKey, error) {
	if !isKeyHash(keyHash) {
		return nil, ErrKeyNotFound
	}
	vk, err := m.store.Get(ctx, keyHash)
	if err != nil {
		return nil, err
	}
	return vk.Clone(), nil
}

// Delete revokes (soft-deletes) a virtual key by hash. Revoked keys can never
// be used again.
func (m *Manager) Delete(ctx context.Context, keyHash string) error {
	_, err := m.update(ctx, normalizeHash(keyHash), func(vk *VirtualKey) error {
		vk.Status = StatusDeleted
		return nil
	})
	return err
}

// Block temporarily disables a key; Unblock re-enables it.
func (m *Manager) Block(ctx context.Context, keyHash string) error {
	return m.setBlocked(ctx, keyHash, true)
}

// Unblock re-enables a blocked key.
func (m *Manager) Unblock(ctx context.Context, keyHash string) error {
	return m.setBlocked(ctx, keyHash, false)
}

func (m *Manager) setBlocked(ctx context.Context, keyHash string, blocked bool) error {
	_, err := m.update(ctx, normalizeHash(keyHash), func(vk *VirtualKey) error {
		if vk.Status == StatusDeleted {
			return ErrKeyRevoked
		}
		vk.Blocked = blocked
		return nil
	})
	return err
}

// Update applies a partial update to a key and returns the new info.
func (m *Manager) Update(ctx context.Context, keyHash string, req *UpdateRequest) (*InfoResponse, error) {
	if req == nil {
		return nil, invalid("body", "missing")
	}
	if req.Models != nil {
		if err := validList("models", *req.Models, maxModels, maxModelLen); err != nil {
			return nil, err
		}
	}
	if req.Aliases != nil {
		if err := validList("aliases", *req.Aliases, maxAliases, maxModelLen); err != nil {
			return nil, err
		}
	}
	if req.MaxBudget != nil {
		if err := validBudget("max_budget", *req.MaxBudget); err != nil {
			return nil, err
		}
	}
	if req.RateLimitRPS != nil {
		if err := validRPS(*req.RateLimitRPS); err != nil {
			return nil, err
		}
	}
	if req.RateLimitTPM != nil {
		if err := validTPM(*req.RateLimitTPM); err != nil {
			return nil, err
		}
	}
	if req.Role != nil {
		if err := validRole(*req.Role); err != nil {
			return nil, err
		}
	}
	if len(req.Metadata) > maxMetadataKeys {
		return nil, invalid("metadata", fmt.Sprintf("more than %d keys", maxMetadataKeys))
	}
	var lifetime, budgetPeriod time.Duration
	var err error
	if req.Duration != nil {
		if lifetime, err = ParseDuration(*req.Duration); err != nil {
			return nil, invalid("duration", err.Error())
		}
	}
	if req.BudgetDuration != nil {
		if budgetPeriod, err = ParseDuration(*req.BudgetDuration); err != nil {
			return nil, invalid("budget_duration", err.Error())
		}
	}

	now := m.now().UTC()
	vk, err := m.update(ctx, normalizeHash(keyHash), func(vk *VirtualKey) error {
		if vk.Status == StatusDeleted {
			return ErrKeyRevoked
		}
		if req.Models != nil {
			vk.Models = append([]string(nil), (*req.Models)...)
		}
		if req.Aliases != nil {
			vk.Aliases = append([]string(nil), (*req.Aliases)...)
		}
		if req.MaxBudget != nil {
			vk.MaxBudget = *req.MaxBudget
		}
		if req.Duration != nil {
			vk.ExpiresAt = time.Time{}
			if lifetime > 0 {
				vk.ExpiresAt = now.Add(lifetime)
			}
		}
		if req.BudgetDuration != nil {
			vk.BudgetDuration, vk.BudgetResetAt = "", time.Time{}
			if budgetPeriod > 0 {
				vk.BudgetDuration = strings.TrimSpace(*req.BudgetDuration)
				vk.BudgetResetAt = now.Add(budgetPeriod)
			}
		}
		if req.Metadata != nil {
			vk.Metadata = maps.Clone(req.Metadata)
			// Keep the typed limits unless explicitly changed below or
			// supplied through metadata.
			if _, ok := req.Metadata[MetadataRateLimitRPS]; ok && req.RateLimitRPS == nil {
				vk.RateLimitRPS = 0
			}
			if _, ok := req.Metadata[MetadataRateLimitTPM]; ok && req.RateLimitTPM == nil {
				vk.RateLimitTPM = 0
			}
		}
		if req.RateLimitRPS != nil {
			vk.RateLimitRPS = *req.RateLimitRPS
		}
		if req.RateLimitTPM != nil {
			vk.RateLimitTPM = *req.RateLimitTPM
		}
		if req.Blocked != nil {
			vk.Blocked = *req.Blocked
		}
		if req.Role != nil {
			if *req.Role == RoleTeamAdmin && vk.TeamID == "" {
				return invalid("role", "team_admin keys require a team_id")
			}
			vk.Role = *req.Role
		}
		if req.ResetSpend {
			vk.Spend = 0
		}
		return applyRateLimitMetadata(vk)
	})
	if err != nil {
		return nil, err
	}
	return infoFromKey(vk, now), nil
}

// Regenerate rotates a key: a new plaintext key with identical settings (and
// current spend) is issued and the old key is revoked. The new plaintext key
// is returned exactly once.
func (m *Manager) Regenerate(ctx context.Context, keyHash string) (*GenerateResponse, error) {
	keyHash = normalizeHash(keyHash)
	old, err := m.get(ctx, keyHash)
	if err != nil {
		return nil, err
	}
	if err := old.usable(m.now()); err != nil && !errors.Is(err, ErrKeyBlocked) {
		return nil, err
	}
	key, err := newPlaintextKey()
	if err != nil {
		return nil, err
	}
	nk := old.Clone()
	now := m.now().UTC()
	nk.KeyHash = HashKey(key)
	nk.HashedKey = nk.KeyHash
	nk.Prefix = key[:prefixHintLen]
	nk.CreatedAt, nk.CreatedAtMs, nk.UpdatedAt = now, now.UnixMilli(), now
	if nk.Metadata == nil {
		nk.Metadata = map[string]interface{}{}
	}
	nk.Metadata["rotated_from"] = old.KeyHash
	if err := m.store.Create(ctx, nk.Clone()); err != nil {
		return nil, fmt.Errorf("keymanager: store key: %w", err)
	}
	if err := m.Delete(ctx, keyHash); err != nil {
		// Roll back so we never leave two live keys behind.
		_ = m.Delete(ctx, nk.KeyHash)
		return nil, err
	}
	expires := ""
	if !nk.ExpiresAt.IsZero() {
		expires = nk.ExpiresAt.Format(time.RFC3339)
	}
	return &GenerateResponse{KeyHash: nk.KeyHash, Key: key, Token: key, Expires: expires, Prefix: nk.Prefix}, nil
}

// Info retrieves key metadata by hash. It never returns the plaintext key.
func (m *Manager) Info(ctx context.Context, keyHash string) (*InfoResponse, error) {
	vk, err := m.get(ctx, normalizeHash(keyHash))
	if err != nil {
		return nil, err
	}
	return infoFromKey(vk, m.now()), nil
}

// KeyFilter restricts List results. Empty fields match everything.
type KeyFilter struct {
	TeamID         string
	UserID         string
	IncludeRevoked bool
}

// List returns info for all keys matching filter, newest first.
func (m *Manager) List(ctx context.Context, filter KeyFilter) ([]*InfoResponse, error) {
	keys, err := m.store.List(ctx)
	if err != nil {
		return nil, err
	}
	now := m.now()
	out := make([]*InfoResponse, 0, len(keys))
	for _, vk := range keys {
		if vk == nil {
			continue
		}
		if filter.TeamID != "" && vk.TeamID != filter.TeamID {
			continue
		}
		if filter.UserID != "" && vk.UserID != filter.UserID {
			continue
		}
		if !filter.IncludeRevoked && vk.Status == StatusDeleted {
			continue
		}
		out = append(out, infoFromKey(vk, now))
	}
	sortInfos(out)
	return out, nil
}

func sortInfos(infos []*InfoResponse) {
	slices.SortFunc(infos, func(a, b *InfoResponse) int {
		if c := b.Created.Compare(a.Created); c != 0 {
			return c
		}
		return strings.Compare(a.KeyHash, b.KeyHash)
	})
}

// lookup finds the stored key for a plaintext key and verifies the hash in
// constant time.
func (m *Manager) lookup(ctx context.Context, key string) (*VirtualKey, error) {
	key = stripBearer(key)
	if key == "" {
		return nil, ErrEmptyKey
	}
	h := HashKey(key)
	vk, err := m.store.Get(ctx, h)
	if err != nil {
		return nil, err
	}
	if vk == nil || subtle.ConstantTimeCompare([]byte(vk.KeyHash), []byte(h)) != 1 {
		return nil, ErrKeyNotFound
	}
	return vk.Clone(), nil
}

// Validate authenticates a plaintext key for gateway use. It rejects
// unknown, revoked, blocked and expired keys and keys whose budget is
// exhausted (ErrBudgetExceeded). The returned key is a private copy whose
// Metadata carries "rate_limit_rps"/"rate_limit_tpm" when per-key limits are
// configured. An optional "Bearer " prefix is ignored.
func (m *Manager) Validate(ctx context.Context, key string) (*VirtualKey, error) {
	vk, err := m.lookup(ctx, key)
	if err != nil {
		return nil, err
	}
	now := m.now()
	if err := vk.usable(now); err != nil {
		return nil, err
	}
	if vk.MaxBudget > 0 && vk.EffectiveSpend(now) >= vk.MaxBudget {
		return nil, ErrBudgetExceeded
	}
	if vk.BudgetDuration != "" && !vk.BudgetResetAt.IsZero() && !now.Before(vk.BudgetResetAt) {
		vk.Spend = 0
	}
	return vk, nil
}

// validateForManagement authenticates a key for the management API; unlike
// Validate it does not reject keys that exhausted their budget.
func (m *Manager) validateForManagement(ctx context.Context, key string) (*VirtualKey, error) {
	vk, err := m.lookup(ctx, key)
	if err != nil {
		return nil, err
	}
	if err := vk.usable(m.now()); err != nil {
		return nil, err
	}
	return vk, nil
}

// CheckBudget returns ErrBudgetExceeded if the key (plaintext or hash) has
// exhausted its budget, or another error if it cannot be found.
func (m *Manager) CheckBudget(ctx context.Context, keyOrHash string) error {
	vk, err := m.get(ctx, m.resolveHash(keyOrHash))
	if err != nil {
		return err
	}
	if vk.MaxBudget > 0 && vk.EffectiveSpend(m.now()) >= vk.MaxBudget {
		return ErrBudgetExceeded
	}
	return nil
}

// RecordSpend adds usd to the key's spend. keyOrHash may be the plaintext
// key (with or without "Bearer ") or its KeyHash. Spend is always recorded
// (the cost was incurred); use CheckBudget/Validate to enforce the budget
// on subsequent requests. Periodic budgets are reset when due.
func (m *Manager) RecordSpend(ctx context.Context, keyOrHash string, usd float64) error {
	_, err := m.RecordSpendByHash(ctx, m.resolveHash(keyOrHash), usd)
	return err
}

// RecordSpendByHash adds usd to the spend of the key with the given hash and
// returns the updated key.
func (m *Manager) RecordSpendByHash(ctx context.Context, keyHash string, usd float64) (*VirtualKey, error) {
	if math.IsNaN(usd) || math.IsInf(usd, 0) || usd < 0 {
		return nil, ErrInvalidAmount
	}
	return m.update(ctx, normalizeHash(keyHash), func(vk *VirtualKey) error {
		now := m.now().UTC()
		if vk.BudgetDuration != "" && !vk.BudgetResetAt.IsZero() && !now.Before(vk.BudgetResetAt) {
			vk.Spend = 0
			if period, err := ParseDuration(vk.BudgetDuration); err == nil && period > 0 {
				// Advance to the next reset boundary after now.
				elapsed := now.Sub(vk.BudgetResetAt)
				vk.BudgetResetAt = vk.BudgetResetAt.Add((elapsed/period + 1) * period)
			}
		}
		vk.Spend += usd
		if math.IsInf(vk.Spend, 0) {
			vk.Spend = math.MaxFloat64
		}
		return nil
	})
}

func (m *Manager) resolveHash(keyOrHash string) string {
	s := stripBearer(keyOrHash)
	if IsVirtualKey(s) {
		return HashKey(s)
	}
	return normalizeHash(s)
}

// ParseKeyOrHash extracts the key hash from a request: an explicit key_hash
// wins, then token, then key. It returns "" if nothing usable was supplied.
func ParseKeyOrHash(mgr *Manager, key, keyHash, token string) string {
	if keyHash = strings.TrimSpace(keyHash); keyHash != "" {
		h := normalizeHash(keyHash)
		if !isKeyHash(h) {
			return ""
		}
		return h
	}
	if token = stripBearer(token); token != "" {
		return HashKey(token)
	}
	if key = stripBearer(key); key != "" {
		return HashKey(key)
	}
	return ""
}

func normalizeHash(h string) string { return strings.ToLower(strings.TrimSpace(h)) }

func isKeyHash(h string) bool {
	if len(h) != hashHexLen {
		return false
	}
	for i := 0; i < len(h); i++ {
		c := h[i]
		if !(c >= '0' && c <= '9' || c >= 'a' && c <= 'f') {
			return false
		}
	}
	return true
}

// stripBearer trims whitespace and an optional, case-insensitive "Bearer "
// scheme prefix.
func stripBearer(s string) string {
	s = strings.TrimSpace(s)
	if len(s) > 7 && strings.EqualFold(s[:7], "bearer ") {
		s = strings.TrimSpace(s[7:])
	}
	return s
}

// IsVirtualKey reports whether an Authorization header value or bare token is
// an AeroLLM virtual key.
//
// Exact semantics: leading/trailing whitespace and an optional,
// case-insensitive "Bearer " scheme are ignored; the remaining token matches
// if and only if it starts with VirtualKeyPrefix ("sk-aero-") and has at
// least one character after it. In particular generic "sk-" keys such as the
// default static admin key "sk-demo" or upstream provider keys are NOT
// virtual keys and must be handled by the static-key path.
func IsVirtualKey(auth string) bool {
	tok := stripBearer(auth)
	return len(tok) > len(VirtualKeyPrefix) && strings.HasPrefix(tok, VirtualKeyPrefix)
}
