// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "AeroLLM Contributors",
            "url": "https://github.com/ayoubzulfiqar/aerollm",
            "email": "contact@ayoubzulfiqar.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://github.com/ayoubzulfiqar/aerollm/blob/main/LICENSE"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/config/update": {
            "post": {
                "description": "Merges a partial JSON config onto the active one (arrays such as providers are replaced), validates it, and hot-reloads the provider registry without dropping connections. Secrets echoed back as \"***REDACTED***\" keep their current value. Durations are nanoseconds.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Update config",
                "parameters": [
                    {
                        "description": "Partial or full configuration",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/config.Config"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/config/yaml": {
            "get": {
                "description": "Returns the active configuration (as JSON) with every secret redacted.",
                "tags": [
                    "config"
                ],
                "summary": "Get active config",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/config.Config"
                        }
                    }
                }
            }
        },
        "/global/spend/logs": {
            "get": {
                "description": "Returns paginated, detailed transaction logs for a specific key or customer.",
                "tags": [
                    "analytics"
                ],
                "summary": "Get spend logs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by api_key, customer_id, or team_id",
                        "name": "filter",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number (default 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Entries per page (default 50, max 500)",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/analytics.SpendLogsResponse"
                        }
                    }
                }
            }
        },
        "/global/spend/report": {
            "get": {
                "description": "Aggregates spend over a time range, grouped by api_key, customer, team, or model.",
                "tags": [
                    "analytics"
                ],
                "summary": "Get spend report",
                "parameters": [
                    {
                        "type": "string",
                        "description": "RFC3339 start timestamp",
                        "name": "start",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "RFC3339 end timestamp",
                        "name": "end",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Group by: api_key, customer, team, model",
                        "name": "group_by",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Optional filter value",
                        "name": "filter",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/analytics.SpendReport"
                        }
                    }
                }
            }
        },
        "/key/delete": {
            "post": {
                "description": "Soft-delete a virtual key.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "keys"
                ],
                "summary": "Delete virtual key",
                "parameters": [
                    {
                        "description": "Delete key request",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/keymanager.DeleteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/key/generate": {
            "post": {
                "description": "Create a new virtual key with allowed models, TTL, and budget limits.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "keys"
                ],
                "summary": "Generate virtual key",
                "parameters": [
                    {
                        "description": "Generate key request",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/keymanager.GenerateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/keymanager.GenerateResponse"
                        }
                    }
                }
            }
        },
        "/key/info": {
            "post": {
                "description": "Get usage, budget, and metadata for a specific virtual key.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "keys"
                ],
                "summary": "Get key info",
                "parameters": [
                    {
                        "description": "Key info request",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/keymanager.InfoRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/keymanager.InfoResponse"
                        }
                    }
                }
            }
        },
        "/model/info": {
            "get": {
                "description": "Returns all currently loaded models, their providers, and capabilities.",
                "tags": [
                    "config"
                ],
                "summary": "Get model info",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/team/create": {
            "post": {
                "description": "Create a new team for an agency.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "teams"
                ],
                "summary": "Create team",
                "parameters": [
                    {
                        "description": "Team creation request",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/keymanager.Team"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/keymanager.Team"
                        }
                    }
                }
            }
        },
        "/team/info": {
            "get": {
                "description": "Get a team's budget, spend and key count.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "teams"
                ],
                "summary": "Get team info",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/keymanager.TeamInfoResponse"
                        }
                    }
                }
            }
        },
        "/team/update": {
            "post": {
                "description": "Update an existing team's details.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "teams"
                ],
                "summary": "Update team",
                "parameters": [
                    {
                        "description": "Team update request",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/keymanager.Team"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/keymanager.Team"
                        }
                    }
                }
            }
        },
        "/user/info": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get user info",
                "parameters": [
                    {
                        "description": "User info request",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/keymanager.InfoRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/keymanager.User"
                        }
                    }
                }
            }
        },
        "/v1/audio/transcriptions": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "audio"
                ],
                "summary": "Transcribe audio",
                "parameters": [
                    {
                        "description": "Audio transcription request",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.AudioRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.AudioResponse"
                        }
                    }
                }
            }
        },
        "/v1/batches": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "batches"
                ],
                "summary": "List batches",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cursor: last batch ID of the previous page",
                        "name": "after",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size (1-100, default 20)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {}
            },
            "post": {
                "description": "Create a batch job from JSONL input (multipart field \"file\", or JSON {\"input\": \"\u003cjsonl\u003e\", \"metadata\": {}, \"completion_window\": \"24h\"}). Each line is {\"custom_id\",\"method\":\"POST\",\"url\":\"/v1/chat/completions\",\"body\":{...}}.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "batches"
                ],
                "summary": "Create batch",
                "parameters": [
                    {
                        "type": "file",
                        "description": "JSONL file containing batch requests",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.BatchObject"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/batches/{batch_id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "batches"
                ],
                "summary": "Get batch status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Batch ID",
                        "name": "batch_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.BatchObject"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/batches/{batch_id}/cancel": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "batches"
                ],
                "summary": "Cancel batch",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Batch ID",
                        "name": "batch_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.BatchObject"
                        }
                    }
                }
            }
        },
        "/v1/batches/{batch_id}/results": {
            "get": {
                "description": "Returns the output JSONL (available for completed, cancelled and expired batches).",
                "produces": [
                    "application/jsonl"
                ],
                "tags": [
                    "batches"
                ],
                "summary": "Get batch results",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Batch ID",
                        "name": "batch_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/v1/cache": {
            "delete": {
                "description": "Clears the cache. Target a type via ?type=semantic|exact|all (default all).",
                "tags": [
                    "cache"
                ],
                "summary": "Clear cache",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cache type to clear: 'exact', 'semantic', or 'all' (default: all)",
                        "name": "type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/v1/cache/inspect": {
            "get": {
                "description": "Returns a paginated list of cached keys (never payloads).",
                "tags": [
                    "cache"
                ],
                "summary": "Inspect cache entries",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cache type: 'exact' (default) or 'semantic'",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Pagination cursor (default: \\",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size (default: 50, max: 500)",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.CacheInspectResponse"
                        }
                    }
                }
            }
        },
        "/v1/cache/stats": {
            "get": {
                "description": "Returns statistics about the exact-match and semantic caches (entries, hit/miss rates).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cache"
                ],
                "summary": "Get cache statistics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.CacheStatsResponse"
                        }
                    }
                }
            }
        },
        "/v1/chat/completions": {
            "post": {
                "description": "Send a chat completion request to an LLM provider. Set stream=true for Server-Sent Events.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chat"
                ],
                "summary": "Chat completion",
                "parameters": [
                    {
                        "description": "Chat completion request",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.LLMRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.LLMResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/embeddings": {
            "post": {
                "description": "Generate embeddings for the given input.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "embeddings"
                ],
                "summary": "Create embeddings",
                "parameters": [
                    {
                        "description": "Embeddings request",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.EmbeddingRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.EmbeddingResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/images/generations": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "images"
                ],
                "summary": "Generate image",
                "parameters": [
                    {
                        "description": "Image generation request",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ImageRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ImageResponse"
                        }
                    }
                }
            }
        },
        "/v1/messages": {
            "post": {
                "description": "Anthropic Messages API compatible endpoint, served through the gateway's routing, caching and accounting. Supports stream=true.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chat"
                ],
                "summary": "Anthropic-style messages",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.anthropicResponse"
                        }
                    }
                }
            }
        },
        "/v1/models": {
            "get": {
                "description": "Lists the models the gateway can route to (OpenAI-compatible).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "models"
                ],
                "summary": "List models",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ModelList"
                        }
                    }
                }
            }
        },
        "/v1/responses": {
            "post": {
                "description": "Create a response using the OpenAI Responses API.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "responses"
                ],
                "summary": "Create response",
                "parameters": [
                    {
                        "description": "Responses request",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ResponsesRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ResponsesResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "analytics.LogEntry": {
            "type": "object",
            "properties": {
                "api_key": {
                    "type": "string"
                },
                "cost_usd": {
                    "type": "number"
                },
                "customer_id": {
                    "type": "string"
                },
                "input_tokens": {
                    "type": "integer"
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": true
                },
                "model": {
                    "type": "string"
                },
                "output_tokens": {
                    "type": "integer"
                },
                "provider": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                },
                "team_id": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "analytics.SpendBucket": {
            "type": "object",
            "properties": {
                "cost_usd": {
                    "type": "number"
                },
                "input_tokens": {
                    "type": "integer"
                },
                "output_tokens": {
                    "type": "integer"
                },
                "requests": {
                    "type": "integer"
                },
                "total_tokens": {
                    "type": "integer"
                }
            }
        },
        "analytics.SpendLogsResponse": {
            "type": "object",
            "properties": {
                "has_more": {
                    "type": "boolean"
                },
                "logs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/analytics.LogEntry"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "analytics.SpendReport": {
            "type": "object",
            "properties": {
                "by_api_key": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/analytics.SpendBucket"
                    }
                },
                "by_customer": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/analytics.SpendBucket"
                    }
                },
                "by_model": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/analytics.SpendBucket"
                    }
                },
                "by_provider": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/analytics.SpendBucket"
                    }
                },
                "by_team": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/analytics.SpendBucket"
                    }
                },
                "data_since": {
                    "description": "DataSince is the timestamp of the oldest retained entry; spend before\nit has been evicted from the in-memory window.",
                    "type": "string"
                },
                "generated_at": {
                    "type": "string"
                },
                "time_range": {
                    "$ref": "#/definitions/analytics.TimeRange"
                },
                "total_cost_usd": {
                    "type": "number"
                },
                "total_requests": {
                    "type": "integer"
                },
                "total_tokens": {
                    "$ref": "#/definitions/analytics.SpendTokens"
                }
            }
        },
        "analytics.SpendTokens": {
            "type": "object",
            "properties": {
                "input": {
                    "type": "integer"
                },
                "output": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "analytics.TimeRange": {
            "type": "object",
            "properties": {
                "end": {
                    "type": "string"
                },
                "start": {
                    "type": "string"
                }
            }
        },
        "api.BatchObject": {
            "type": "object",
            "properties": {
                "cancelled_at": {
                    "type": "integer"
                },
                "cancelling_at": {
                    "type": "integer"
                },
                "completed_at": {
                    "type": "integer"
                },
                "completed_requests": {
                    "type": "integer"
                },
                "completion_window": {
                    "type": "string"
                },
                "created_at": {
                    "type": "integer"
                },
                "endpoint": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                },
                "error_file_id": {
                    "type": "string"
                },
                "errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/batch.BatchError"
                    }
                },
                "expired_at": {
                    "type": "integer"
                },
                "expires_at": {
                    "type": "integer"
                },
                "failed_at": {
                    "type": "integer"
                },
                "failed_requests": {
                    "type": "integer"
                },
                "finalizing_at": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "in_progress_at": {
                    "type": "integer"
                },
                "input_file_id": {
                    "type": "string"
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "object": {
                    "type": "string"
                },
                "output_file_id": {
                    "type": "string"
                },
                "request_counts": {
                    "$ref": "#/definitions/batch.RequestCounts"
                },
                "status": {
                    "type": "string"
                },
                "total_requests": {
                    "description": "Flat counters kept for backward compatibility.",
                    "type": "integer"
                }
            }
        },
        "api.CacheInspectEntry": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "key": {
                    "type": "string"
                },
                "model": {
                    "type": "string"
                },
                "semantic": {
                    "type": "boolean"
                },
                "token_count": {
                    "type": "integer"
                }
            }
        },
        "api.CacheInspectResponse": {
            "type": "object",
            "properties": {
                "cursor": {
                    "type": "string"
                },
                "entries": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.CacheInspectEntry"
                    }
                }
            }
        },
        "api.CacheStatsResponse": {
            "type": "object",
            "properties": {
                "exact": {
                    "type": "object",
                    "properties": {
                        "error": {
                            "type": "string"
                        },
                        "hit_rate": {
                            "type": "number"
                        },
                        "hits": {
                            "type": "integer"
                        },
                        "misses": {
                            "type": "integer"
                        },
                        "total_entries": {
                            "type": "integer"
                        },
                        "truncated": {
                            "type": "boolean"
                        }
                    }
                },
                "semantic": {
                    "type": "object",
                    "properties": {
                        "active_entries": {
                            "type": "integer"
                        },
                        "enabled": {
                            "type": "boolean"
                        },
                        "total_entries": {
                            "type": "integer"
                        }
                    }
                }
            }
        },
        "api.ModelEntry": {
            "type": "object",
            "properties": {
                "created": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "object": {
                    "type": "string"
                },
                "owned_by": {
                    "type": "string"
                }
            }
        },
        "api.ModelList": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.ModelEntry"
                    }
                },
                "object": {
                    "type": "string"
                }
            }
        },
        "api.anthropicBlock": {
            "type": "object",
            "properties": {
                "cache_control": {
                    "$ref": "#/definitions/models.CacheControl"
                },
                "content": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "input": {
                    "type": "object"
                },
                "is_error": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "source": {
                    "$ref": "#/definitions/api.anthropicSource"
                },
                "text": {
                    "type": "string"
                },
                "tool_use_id": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "api.anthropicResponse": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.anthropicBlock"
                    }
                },
                "id": {
                    "type": "string"
                },
                "model": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "stop_reason": {
                    "type": "string"
                },
                "stop_sequence": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "usage": {
                    "$ref": "#/definitions/api.anthropicUsage"
                }
            }
        },
        "api.anthropicSource": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "string"
                },
                "media_type": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "api.anthropicUsage": {
            "type": "object",
            "properties": {
                "input_tokens": {
                    "type": "integer"
                },
                "output_tokens": {
                    "type": "integer"
                }
            }
        },
        "batch.BatchError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "line": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "param": {
                    "type": "string"
                }
            }
        },
        "batch.RequestCounts": {
            "type": "object",
            "properties": {
                "completed": {
                    "type": "integer"
                },
                "failed": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "config.AgentConfig": {
            "type": "object",
            "properties": {
                "cache_tool_results": {
                    "type": "boolean"
                },
                "enabled": {
                    "type": "boolean"
                },
                "max_concurrent": {
                    "type": "integer"
                },
                "max_iterations": {
                    "type": "integer"
                },
                "tool_timeout": {
                    "$ref": "#/definitions/time.Duration"
                }
            }
        },
        "config.AppConfig": {
            "type": "object",
            "properties": {
                "env": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "config.AuthConfig": {
            "type": "object",
            "properties": {
                "admin_keys": {
                    "description": "AdminKeys are additional keys with admin access.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "api_keys": {
                    "description": "APIKeys are static client keys allowed to call the inference endpoints.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "master_key": {
                    "description": "MasterKey grants admin access (key management, config, control plane).\nWhen empty a random key is generated at startup and printed once.",
                    "type": "string"
                }
            }
        },
        "config.CacheConfig": {
            "type": "object",
            "properties": {
                "enabled": {
                    "type": "boolean"
                },
                "exact_prefix": {
                    "type": "string"
                },
                "semantic_embedding_model": {
                    "description": "SemanticEmbeddingModel, when set, embeds prompts for the semantic\ncache through the gateway's embeddings route (otherwise a local\nlexical embedder is used).",
                    "type": "string"
                },
                "semantic_enabled": {
                    "description": "SemanticEnabled turns on similarity-based caching.",
                    "type": "boolean"
                },
                "semantic_prefix": {
                    "type": "string"
                },
                "semantic_threshold": {
                    "type": "number"
                },
                "shared_across_keys": {
                    "description": "SharedAcrossKeys lets different API keys share cache entries. Off by\ndefault so one tenant can never be served another tenant's response.",
                    "type": "boolean"
                },
                "ttl": {
                    "$ref": "#/definitions/time.Duration"
                }
            }
        },
        "config.CallbackDatadogConfig": {
            "type": "object",
            "properties": {
                "api_key": {
                    "type": "string"
                },
                "base_url": {
                    "type": "string"
                },
                "enabled": {
                    "type": "boolean"
                },
                "site": {
                    "type": "string"
                }
            }
        },
        "config.CallbackLangfuseConfig": {
            "type": "object",
            "properties": {
                "api_key": {
                    "description": "APIKey is the legacy single-key form (\"pk:sk\" or the secret key).",
                    "type": "string"
                },
                "base_url": {
                    "type": "string"
                },
                "enabled": {
                    "type": "boolean"
                },
                "project_id": {
                    "type": "string"
                },
                "public_key": {
                    "description": "PublicKey/SecretKey are the Langfuse project key pair (preferred).",
                    "type": "string"
                },
                "secret_key": {
                    "type": "string"
                }
            }
        },
        "config.CallbackWebhookConfig": {
            "type": "object",
            "properties": {
                "enabled": {
                    "type": "boolean"
                },
                "retries": {
                    "type": "integer"
                },
                "retry_delay": {
                    "$ref": "#/definitions/time.Duration"
                },
                "secret": {
                    "type": "string"
                },
                "timeout": {
                    "$ref": "#/definitions/time.Duration"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "config.CallbacksConfig": {
            "type": "object",
            "properties": {
                "datadog": {
                    "$ref": "#/definitions/config.CallbackDatadogConfig"
                },
                "langfuse": {
                    "$ref": "#/definitions/config.CallbackLangfuseConfig"
                },
                "webhook": {
                    "$ref": "#/definitions/config.CallbackWebhookConfig"
                }
            }
        },
        "config.CircuitBreakConfig": {
            "type": "object",
            "properties": {
                "half_open_max_calls": {
                    "type": "integer"
                },
                "max_failures": {
                    "type": "integer"
                },
                "reset_timeout": {
                    "$ref": "#/definitions/time.Duration"
                }
            }
        },
        "config.Config": {
            "type": "object",
            "properties": {
                "agent": {
                    "$ref": "#/definitions/config.AgentConfig"
                },
                "app": {
                    "$ref": "#/definitions/config.AppConfig"
                },
                "auth": {
                    "$ref": "#/definitions/config.AuthConfig"
                },
                "cache": {
                    "$ref": "#/definitions/config.CacheConfig"
                },
                "callbacks": {
                    "$ref": "#/definitions/config.CallbacksConfig"
                },
                "finops": {
                    "$ref": "#/definitions/config.FinopsConfig"
                },
                "guardrails": {
                    "$ref": "#/definitions/config.GuardrailsConfig"
                },
                "logging": {
                    "$ref": "#/definitions/config.LoggingConfig"
                },
                "persistence": {
                    "$ref": "#/definitions/config.PersistenceConfig"
                },
                "plugins": {
                    "$ref": "#/definitions/config.PluginsConfig"
                },
                "providers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/config.ProviderConfig"
                    }
                },
                "rate_limit": {
                    "$ref": "#/definitions/config.RateLimitConfig"
                },
                "redis": {
                    "$ref": "#/definitions/config.RedisConfig"
                },
                "router": {
                    "$ref": "#/definitions/config.RouterConfig"
                },
                "security": {
                    "$ref": "#/definitions/config.SecurityConfig"
                },
                "server": {
                    "$ref": "#/definitions/config.ServerConfig"
                },
                "telemetry": {
                    "$ref": "#/definitions/config.TelemetryConfig"
                },
                "webhooks": {
                    "$ref": "#/definitions/config.WebhooksConfig"
                }
            }
        },
        "config.FinopsConfig": {
            "type": "object",
            "properties": {
                "budget_period": {
                    "description": "BudgetPeriod resets per-key spend: \"lifetime\" (default), \"daily\" or\n\"monthly\" (UTC).",
                    "type": "string"
                },
                "default_max_usd": {
                    "type": "number"
                },
                "enabled": {
                    "type": "boolean"
                }
            }
        },
        "config.GuardrailsConfig": {
            "type": "object",
            "properties": {
                "enabled": {
                    "type": "boolean"
                }
            }
        },
        "config.LoggingConfig": {
            "type": "object",
            "properties": {
                "format": {
                    "type": "string"
                },
                "level": {
                    "type": "string"
                }
            }
        },
        "config.PersistenceConfig": {
            "type": "object",
            "properties": {
                "enabled": {
                    "type": "boolean"
                },
                "path": {
                    "description": "Path of the database file (default \u003cAEROLLM_STATE_DIR\u003e/gateway.db).",
                    "type": "string"
                }
            }
        },
        "config.PluginHookConfig": {
            "type": "object",
            "properties": {
                "file": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                }
            }
        },
        "config.PluginToolConfig": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "file": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "parameters": {
                    "type": "object",
                    "additionalProperties": true
                }
            }
        },
        "config.PluginsConfig": {
            "type": "object",
            "properties": {
                "allow_clock": {
                    "description": "AllowClock / AllowRandom expose real clocks / crypto randomness to\nguests (deterministic fakes otherwise).",
                    "type": "boolean"
                },
                "allow_random": {
                    "type": "boolean"
                },
                "dir": {
                    "description": "Dir holds the .wasm files; tool files are resolved inside it only.",
                    "type": "string"
                },
                "hooks": {
                    "description": "Hooks run, in order, on every chat request (OnRequest) and\nnon-streaming response (OnResponse).",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/config.PluginHookConfig"
                    }
                },
                "max_concurrent": {
                    "description": "MaxConcurrent bounds simultaneous runs (0 = runtime default).",
                    "type": "integer"
                },
                "memory_mib": {
                    "description": "MemoryMiB caps each module's linear memory.",
                    "type": "integer"
                },
                "timeout": {
                    "description": "Timeout bounds one tool invocation.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/time.Duration"
                        }
                    ]
                },
                "tools": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/config.PluginToolConfig"
                    }
                }
            }
        },
        "config.ProviderConfig": {
            "type": "object",
            "properties": {
                "api_key": {
                    "type": "string"
                },
                "api_version": {
                    "description": "APIVersion is sent as ?api-version= for Azure OpenAI deployment URLs.",
                    "type": "string"
                },
                "base_url": {
                    "type": "string"
                },
                "models": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "rate_limit_rps": {
                    "type": "number"
                },
                "timeout": {
                    "$ref": "#/definitions/time.Duration"
                },
                "type": {
                    "type": "string"
                },
                "weight": {
                    "type": "integer"
                }
            }
        },
        "config.RateLimitConfig": {
            "type": "object",
            "properties": {
                "burst_multiplier": {
                    "type": "integer"
                },
                "default_rps": {
                    "type": "number"
                },
                "default_tpm": {
                    "description": "DefaultTPM is the advertised tokens-per-minute limit.",
                    "type": "integer"
                },
                "strategy": {
                    "type": "string"
                }
            }
        },
        "config.RedisConfig": {
            "type": "object",
            "properties": {
                "addr": {
                    "type": "string"
                },
                "db": {
                    "type": "integer"
                },
                "min_idle_conns": {
                    "type": "integer"
                },
                "password": {
                    "type": "string"
                },
                "pool_size": {
                    "type": "integer"
                },
                "required": {
                    "description": "Required makes startup fail when Redis is unreachable. When false the\ngateway starts in degraded mode (in-memory limiter, no exact cache).",
                    "type": "boolean"
                }
            }
        },
        "config.RouterConfig": {
            "type": "object",
            "properties": {
                "circuit_break": {
                    "$ref": "#/definitions/config.CircuitBreakConfig"
                },
                "health_check_interval": {
                    "description": "HealthCheckInterval actively probes providers (cheap model-list GETs)\nso readiness and routing reflect upstream health. 0 disables.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/time.Duration"
                        }
                    ]
                },
                "max_attempts": {
                    "description": "MaxAttempts bounds how many providers are tried for one request when\nearlier attempts fail with retryable errors.",
                    "type": "integer"
                },
                "max_retry_wait": {
                    "description": "MaxRetryWait is the longest upstream Retry-After the router will wait\nout before retrying when no other provider is left (0 disables).",
                    "allOf": [
                        {
                            "$ref": "#/definitions/time.Duration"
                        }
                    ]
                },
                "strategy": {
                    "type": "string"
                }
            }
        },
        "config.SecurityConfig": {
            "type": "object",
            "properties": {
                "cors_allowed_origins": {
                    "description": "CORSAllowedOrigins lists origins allowed to call the API from browsers.\nEmpty disables CORS; \"*\" allows any origin (credentials never allowed).",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "enable_pprof": {
                    "description": "EnablePprof exposes net/http/pprof on localhost:6060.",
                    "type": "boolean"
                },
                "public_metrics": {
                    "description": "PublicMetrics serves /metrics without authentication.",
                    "type": "boolean"
                }
            }
        },
        "config.ServerConfig": {
            "type": "object",
            "properties": {
                "idle_timeout": {
                    "$ref": "#/definitions/time.Duration"
                },
                "max_body_bytes": {
                    "description": "MaxBodyBytes caps request bodies on JSON endpoints.",
                    "type": "integer"
                },
                "port": {
                    "type": "integer"
                },
                "read_header_timeout": {
                    "$ref": "#/definitions/time.Duration"
                },
                "read_timeout": {
                    "$ref": "#/definitions/time.Duration"
                },
                "shutdown_timeout": {
                    "$ref": "#/definitions/time.Duration"
                },
                "write_timeout": {
                    "description": "WriteTimeout bounds non-streaming responses. Streaming (SSE) responses\nlift the deadline per request so long generations are not cut off.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/time.Duration"
                        }
                    ]
                }
            }
        },
        "config.TelemetryConfig": {
            "type": "object",
            "properties": {
                "enabled": {
                    "type": "boolean"
                },
                "exporter": {
                    "type": "string"
                },
                "otlp_addr": {
                    "type": "string"
                },
                "sample_rate": {
                    "type": "number"
                },
                "service_name": {
                    "type": "string"
                }
            }
        },
        "config.WebhooksConfig": {
            "type": "object",
            "properties": {
                "enabled": {
                    "type": "boolean"
                }
            }
        },
        "keymanager.DeleteRequest": {
            "type": "object",
            "properties": {
                "key": {
                    "type": "string"
                },
                "key_hash": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "keymanager.GenerateRequest": {
            "type": "object",
            "properties": {
                "aliases": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "blocked": {
                    "type": "boolean"
                },
                "budget_duration": {
                    "type": "string"
                },
                "duration": {
                    "type": "string"
                },
                "max_budget": {
                    "type": "number"
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": true
                },
                "models": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "rate_limit_rps": {
                    "type": "number"
                },
                "rate_limit_tpm": {
                    "type": "integer"
                },
                "role": {
                    "$ref": "#/definitions/keymanager.KeyRole"
                },
                "team_id": {
                    "type": "string"
                },
                "tenant_id": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "keymanager.GenerateResponse": {
            "type": "object",
            "properties": {
                "expires": {
                    "description": "Expires is RFC 3339, or \"\" when the key never expires.",
                    "type": "string"
                },
                "key": {
                    "type": "string"
                },
                "key_hash": {
                    "type": "string"
                },
                "prefix": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "keymanager.InfoRequest": {
            "type": "object",
            "properties": {
                "key": {
                    "type": "string"
                },
                "key_hash": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "keymanager.InfoResponse": {
            "type": "object",
            "properties": {
                "aliases": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "blocked": {
                    "type": "boolean"
                },
                "budget_duration": {
                    "type": "string"
                },
                "budget_reset_at": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "expires_at": {
                    "type": "string"
                },
                "key_hash": {
                    "type": "string"
                },
                "max_budget": {
                    "type": "number"
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": true
                },
                "models": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "prefix": {
                    "type": "string"
                },
                "rate_limit_rps": {
                    "type": "number"
                },
                "rate_limit_tpm": {
                    "type": "integer"
                },
                "role": {
                    "$ref": "#/definitions/keymanager.KeyRole"
                },
                "spend": {
                    "type": "number"
                },
                "status": {
                    "$ref": "#/definitions/keymanager.KeyStatus"
                },
                "team_id": {
                    "type": "string"
                },
                "tenant_id": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "keymanager.KeyRole": {
            "type": "string",
            "enum": [
                "",
                "team_admin"
            ],
            "x-enum-varnames": [
                "RoleMember",
                "RoleTeamAdmin"
            ]
        },
        "keymanager.KeyStatus": {
            "type": "string",
            "enum": [
                "active",
                "deleted",
                "expired"
            ],
            "x-enum-varnames": [
                "StatusActive",
                "StatusDeleted",
                "StatusExpired"
            ]
        },
        "keymanager.Team": {
            "type": "object",
            "properties": {
                "budget": {
                    "type": "number"
                },
                "budget_duration": {
                    "description": "BudgetDuration, if set (e.g. \"30d\"), resets Spend periodically.",
                    "type": "string"
                },
                "budget_reset_at": {
                    "description": "BudgetResetAt is when Spend is next reset (zero if no BudgetDuration).",
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "members": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": true
                },
                "name": {
                    "type": "string"
                },
                "spend": {
                    "description": "Spend is the accumulated spend in USD of all keys of the team in the\ncurrent budget period.",
                    "type": "number"
                }
            }
        },
        "keymanager.TeamInfoResponse": {
            "type": "object",
            "properties": {
                "budget": {
                    "type": "number"
                },
                "budget_duration": {
                    "description": "BudgetDuration, if set (e.g. \"30d\"), resets Spend periodically.",
                    "type": "string"
                },
                "budget_exceeded": {
                    "description": "BudgetExceeded reports whether keys of the team are currently\nrejected because of the team budget.",
                    "type": "boolean"
                },
                "budget_reset_at": {
                    "description": "BudgetResetAt is when Spend is next reset (zero if no BudgetDuration).",
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "keys": {
                    "description": "Keys is the number of non-revoked keys assigned to the team.",
                    "type": "integer"
                },
                "members": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": true
                },
                "name": {
                    "type": "string"
                },
                "remaining_budget": {
                    "description": "RemainingBudget is Budget - Spend (never negative); absent when the\nteam has no budget.",
                    "type": "number"
                },
                "spend": {
                    "description": "Spend is the accumulated spend in USD of all keys of the team in the\ncurrent budget period.",
                    "type": "number"
                }
            }
        },
        "keymanager.User": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": true
                },
                "role": {
                    "type": "string"
                }
            }
        },
        "models.AudioRequest": {
            "type": "object",
            "properties": {
                "file": {
                    "type": "string"
                },
                "model": {
                    "type": "string"
                },
                "prompt": {
                    "type": "string"
                }
            }
        },
        "models.AudioResponse": {
            "type": "object",
            "properties": {
                "text": {
                    "type": "string"
                }
            }
        },
        "models.CacheControl": {
            "type": "object",
            "properties": {
                "type": {
                    "description": "e.g. \"ephemeral\"",
                    "type": "string"
                }
            }
        },
        "models.Choice": {
            "description": "A single response choice.",
            "type": "object",
            "properties": {
                "finish_reason": {
                    "type": "string"
                },
                "index": {
                    "type": "integer"
                },
                "logprobs": {
                    "description": "Logprobs is passed through verbatim when the upstream returns it.",
                    "type": "object"
                },
                "message": {
                    "$ref": "#/definitions/models.Message"
                }
            }
        },
        "models.Embedding": {
            "type": "object",
            "properties": {
                "embedding": {
                    "type": "array",
                    "items": {
                        "type": "number"
                    }
                },
                "index": {
                    "type": "integer"
                },
                "object": {
                    "type": "string"
                }
            }
        },
        "models.EmbeddingRequest": {
            "type": "object",
            "properties": {
                "dimensions": {
                    "type": "integer"
                },
                "encoding_format": {
                    "type": "string"
                },
                "input": {
                    "type": "string"
                },
                "model": {
                    "type": "string"
                },
                "user": {
                    "type": "string"
                }
            }
        },
        "models.EmbeddingResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Embedding"
                    }
                },
                "model": {
                    "type": "string"
                },
                "object": {
                    "type": "string"
                },
                "usage": {
                    "$ref": "#/definitions/models.Usage"
                }
            }
        },
        "models.Image": {
            "type": "object",
            "properties": {
                "b64_json": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "models.ImageRequest": {
            "type": "object",
            "properties": {
                "model": {
                    "type": "string"
                },
                "n": {
                    "type": "integer"
                },
                "prompt": {
                    "type": "string"
                },
                "size": {
                    "type": "string"
                }
            }
        },
        "models.ImageResponse": {
            "type": "object",
            "properties": {
                "created": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Image"
                    }
                }
            }
        },
        "models.JSONSchema": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "schema": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "strict": {
                    "type": "boolean"
                }
            }
        },
        "models.LLMRequest": {
            "description": "Unified chat completion request compatible with OpenAI, Anthropic, and 100+ providers.",
            "type": "object",
            "properties": {
                "frequency_penalty": {
                    "type": "number"
                },
                "logit_bias": {
                    "description": "LogitBias maps token IDs to bias values (-100..100).",
                    "type": "object",
                    "additionalProperties": {
                        "type": "number",
                        "format": "float64"
                    }
                },
                "logprobs": {
                    "description": "Logprobs requests log probabilities of output tokens.",
                    "type": "boolean"
                },
                "max_completion_tokens": {
                    "description": "MaxCompletionTokens is the newer OpenAI name for MaxTokens.",
                    "type": "integer"
                },
                "max_tokens": {
                    "description": "Maximum tokens to generate.",
                    "type": "integer",
                    "example": 4096
                },
                "messages": {
                    "description": "The conversation messages.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Message"
                    }
                },
                "model": {
                    "description": "The model identifier (e.g. \"gpt-4o\", \"claude-3-opus\").",
                    "type": "string",
                    "example": "gpt-4o"
                },
                "n": {
                    "description": "N is the number of choices to generate.",
                    "type": "integer"
                },
                "parallel_tool_calls": {
                    "description": "ParallelToolCalls enables parallel function calling.",
                    "type": "boolean"
                },
                "presence_penalty": {
                    "type": "number"
                },
                "rag_enabled": {
                    "type": "boolean"
                },
                "response_format": {
                    "description": "ResponseFormat controls structured output.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.ResponseFormat"
                        }
                    ]
                },
                "seed": {
                    "description": "Seed requests deterministic sampling.",
                    "type": "integer"
                },
                "stop": {
                    "description": "Stop sequences.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "stream": {
                    "type": "boolean",
                    "example": false
                },
                "stream_options": {
                    "description": "StreamOptions configures streaming (e.g. include_usage).",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.StreamOptions"
                        }
                    ]
                },
                "temperature": {
                    "description": "Sampling temperature (0-2).",
                    "type": "number",
                    "example": 0.7
                },
                "tool_choice": {
                    "description": "ToolChoice controls which (if any) tool is called.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.ToolChoice"
                        }
                    ]
                },
                "tools": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ToolDefinition"
                    }
                },
                "top_logprobs": {
                    "description": "TopLogprobs is the number of most likely tokens to return (0-20).",
                    "type": "integer"
                },
                "top_p": {
                    "description": "Nucleus sampling (0-1).",
                    "type": "number",
                    "example": 1
                },
                "user": {
                    "description": "User is an end-user identifier for abuse monitoring.",
                    "type": "string"
                }
            }
        },
        "models.LLMResponse": {
            "description": "Unified LLM response.",
            "type": "object",
            "properties": {
                "choices": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Choice"
                    }
                },
                "created": {
                    "type": "integer",
                    "example": 1700000000
                },
                "id": {
                    "type": "string",
                    "example": "chatcmpl-123"
                },
                "model": {
                    "type": "string",
                    "example": "gpt-4o"
                },
                "object": {
                    "type": "string",
                    "example": "chat.completion"
                },
                "system_fingerprint": {
                    "type": "string"
                },
                "usage": {
                    "$ref": "#/definitions/models.Usage"
                }
            }
        },
        "models.Message": {
            "type": "object",
            "properties": {
                "cache_control": {
                    "description": "CacheControl enables prompt caching (Anthropic beta feature).\nWhen set to {\"type\":\"ephemeral\"}, Anthropic caches this message to reduce costs.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.CacheControl"
                        }
                    ]
                },
                "content": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "role": {
                    "$ref": "#/definitions/models.MessageRole"
                },
                "tool_call_id": {
                    "type": "string"
                },
                "tool_calls": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ToolCall"
                    }
                },
                "tool_result": {
                    "type": "string"
                }
            }
        },
        "models.MessageRole": {
            "type": "string",
            "enum": [
                "system",
                "user",
                "assistant",
                "tool",
                "developer"
            ],
            "x-enum-varnames": [
                "RoleSystem",
                "RoleUser",
                "RoleAssistant",
                "RoleTool",
                "RoleDeveloper"
            ]
        },
        "models.PromptTokensDetails": {
            "type": "object",
            "properties": {
                "cached_tokens": {
                    "type": "integer"
                }
            }
        },
        "models.ResponseFormat": {
            "type": "object",
            "properties": {
                "json_schema": {
                    "$ref": "#/definitions/models.JSONSchema"
                },
                "type": {
                    "description": "\"json_schema\" | \"json_object\" | \"text\"",
                    "type": "string"
                }
            }
        },
        "models.ResponsesRequest": {
            "type": "object",
            "properties": {
                "input": {
                    "type": "string"
                },
                "model": {
                    "type": "string"
                },
                "previous_response_id": {
                    "type": "string"
                },
                "tools": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ToolDefinition"
                    }
                }
            }
        },
        "models.ResponsesResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "model": {
                    "type": "string"
                },
                "object": {
                    "type": "string"
                },
                "output": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Message"
                    }
                },
                "usage": {
                    "$ref": "#/definitions/models.Usage"
                }
            }
        },
        "models.StreamOptions": {
            "type": "object",
            "properties": {
                "include_usage": {
                    "type": "boolean"
                }
            }
        },
        "models.ToolCall": {
            "type": "object",
            "properties": {
                "function": {
                    "$ref": "#/definitions/models.ToolFunction"
                },
                "id": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "models.ToolChoice": {
            "type": "object",
            "properties": {
                "function": {
                    "description": "Function forces a specific function tool by name.",
                    "type": "string"
                },
                "mode": {
                    "description": "Mode is \"none\", \"auto\" or \"required\" when Function is empty.",
                    "type": "string"
                }
            }
        },
        "models.ToolDefinition": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "parameters": {
                    "type": "object",
                    "additionalProperties": true
                },
                "strict": {
                    "description": "Strict enables OpenAI strict schema adherence.",
                    "type": "boolean"
                }
            }
        },
        "models.ToolFunction": {
            "type": "object",
            "properties": {
                "arguments": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "models.Usage": {
            "description": "Token usage statistics for a completion request.",
            "type": "object",
            "properties": {
                "completion_tokens": {
                    "type": "integer",
                    "example": 50
                },
                "prompt_tokens": {
                    "type": "integer",
                    "example": 100
                },
                "prompt_tokens_details": {
                    "description": "PromptTokensDetails reports cached prompt tokens when known.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.PromptTokensDetails"
                        }
                    ]
                },
                "total_tokens": {
                    "type": "integer",
                    "example": 150
                }
            }
        },
        "time.Duration": {
            "type": "integer",
            "format": "int64",
            "enum": [
                -9223372036854775808,
                9223372036854775807,
                1,
                1000,
                1000000,
                1000000000,
                60000000000,
                3600000000000
            ],
            "x-enum-varnames": [
                "minDuration",
                "maxDuration",
                "Nanosecond",
                "Microsecond",
                "Millisecond",
                "Second",
                "Minute",
                "Hour"
            ]
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "AeroLLM API",
	Description:      "AeroLLM is a high-performance, multi-provider LLM gateway that serves as a drop-in replacement for the LiteLLM proxy. It supports OpenAI- and Anthropic-compatible APIs with streaming, advanced routing and fallback, virtual keys, caching, spend analytics, and async observability callbacks.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
